== Registering a machine to the Red Hat Insights service

Red Hat Insights is now included in every Red Hat Enterprise Linux
subscription.

In most Red Hat Enterprise Linux 8 installations, the insights-client
software will be installed by default. However, the minimal package set
does not include installing the insights-client package and it will
likely need it installed.

Install the insights-client package on the machine.

[source,bash]
----
yum -y install insights-client
----

Next, register your system with Red Hat Insights.

[source,bash]
----
insights-client --register
----

[source,bash]
----
Successfully registered host rhel-e6d30
Automatic scheduling for Insights has been enabled.
Starting to collect Insights data for rhel-e6d30
Uploading Insights data.
Successfully uploaded report from rhel-e6d30 to account 6227255.
View the Red Hat Insights console at https://cloud.redhat.com/insights/
----

From the above output, you can observe that the system has been
successfully registered with the Red Hat Insights service. As part of
the registration, the machine also uploads a report to the Red Hat
Insights service so that it may be analyzed for any Insights.

For future reference, make note of your system hostname.

[source,bash]
----
hostname
----

[source,bash]
----
rhel-e6d30
----

____
_NOTE:_ Your hostname will be different than the one listed in the
output above
____

At any time in the future, you can get information about Insights
registration by using the `+--status+` option to `+insights-client+`.

[source,bash]
----
insights-client --status
----

[source,bash]
----
System is registered locally via .registered file. Registered at 2019-08-14T14:12:37.638768
Insights API confirms registration.
----

Check whether or not SQL Server is running on the machine.

[source,bash]
----
systemctl status mssql-server.service --no-pager
----

<< OUTPUT ABRIDGED >>

Active: failed (Result: exit-code) since Tue 2020-03-10 03:29:37 EDT;
8min ago

<< OUTPUT ABRIDGED >> ```

Verify that the Active status is *Failed (NOT running)*. Let’s have
insights tell us what might be the issue here.
